### ISSUE TITLE
styles should support functions of x or y

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-scatter#32]
all style properties should be able to be passed as functions of x or y like:

```
style= {{
  data: {
    fill: (x) => {return x > 20 ? "red" : "blue"}
  }
}}
```
and evaluated for each data point.  This should be the most straightforward to do with scatter, and can serve as the example for other data types

**Comment by coopy** [comment]
Should this be in alpha, or in a future milestone?

**Comment by boygirl** [comment]
I want to try for alpha, I *think* I can make it.
